export const ADD = 'add'
export const ADD_SINGLE = 'add-single'
export const REMOVE = 'remove'
export const REPLACE_ITEMS = 'replace-items'
export const ADD_ITEMS = 'add-items'
export const REMOVE_ITEMS = 'remove-items'
export const REMOVE_ALL = 'remove-all'
